# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
no_package = True
skip_missing_interpreters = True
env_list = lint, unit, integration

[vars]
src_path = {tox_root}/app
tests_path = {tox_root}/tests
all_path = {[vars]src_path} {[vars]tests_path}

[testenv]
allowlist_externals =
    /bin/bash

set_env =
    PYTHONPATH = {tox_root}

[testenv:format]
description = Apply coding style standards to code
dependency_groups = format
commands =
    ruff format --config pyproject.toml {[vars]all_path}

[testenv:lint]
description = Check code against coding style standards
dependency_groups = lint
commands =
    ruff format --config pyproject.toml {[vars]all_path}
    ruff check --config pyproject.toml --fix {[vars]all_path}
    mypy {[vars]src_path} --ignore-missing

[testenv:unit]
description = Run unit tests
dependency_groups = unit
commands =
    python -m pytest {[vars]tests_path}/unit

[testenv:integration]
description = Run integration tests
dependency_groups = integration
commands =
    python -m pytest -xvv --tb native --log-cli-level=INFO -s {posargs} {[vars]tests_path}/integration
