# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

[tox]
no_package = True
skip_missing_interpreters = True
env_list = lint, unit

[vars]
src_path = {tox_root}/files/scripts
tests_path = {tox_root}/tests
all_path = {[vars]src_path} {[vars]tests_path}

[testenv]
allowlist_externals =
    /bin/bash

set_env =
    PYTHONPATH = {[vars]src_path}

[testenv:format]
description = Apply coding style standards to code
commands =
    pip install ruff
    ruff format --config pyproject.toml {[vars]all_path}

[testenv:lint]
description = Check code against coding style standards
commands =
    pip install ruff mypy
    ruff format --config pyproject.toml {[vars]all_path}
    ruff check --config pyproject.toml --fix {[vars]all_path}

	pip install spark8t==1.4.1
    mypy {[vars]src_path} --ignore-missing

[testenv:unit]
description = Run unit tests
commands =
	pip install pytest lightkube spark8t
	python -m pytest {[vars]tests_path}
