name: Release to GHCR

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 3/edge

permissions:
  contents: read

jobs:
  build:
    name: Build rock
    uses: canonical/data-platform-workflows/.github/workflows/build_rock.yaml@e5539256480675584841600b2f6291c38bc6d4f7 # v50.2.1

  release:
    name: Release rock
    needs:
      - build
    uses: canonical/data-platform-workflows/.github/workflows/release_rock_edge.yaml@e5539256480675584841600b2f6291c38bc6d4f7 # v50.2.1
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
    permissions:
      packages: write # Needed to publish to GitHub Container Registry
      contents: write # Needed to create git tags

  trivy:
    needs: build
    uses: ./.github/workflows/trivy.yaml
    with:
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      submit_dependency_graph: true
    permissions:
      contents: write # dependency graph
      security-events: write
